# Generated by Django 4.2.3 on 2023-08-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_options_account_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('in-active', 'in-active')], default='in-active', max_length=100),
        ),
    ]
